export const coursesItems = [
  {
    name: 'Ethereum and Solidity: The Complete Developer\'s Guide',
    date: '2021',
    time: '24 hours',
    platform: 'Udemy',
    description: 'Design, test, and deploy secure Smart Contracts, and use the latest version of Ethereum and React development tools to create blockchain applications.',
    link: 'https://www.udemy.com/course/ethereum-and-solidity-the-complete-developers-guide/',
    github: 'https://github.com/tonidalmases/kickstart',
  },
  {
    name: 'The Complete 2020 Web Development Bootcamp',
    date: '2020',
    time: '54 hours',
    platform: 'Udemy',
    description: 'Learn the latest frameworks and technologies, including Javascript ES6, React, Bootstrap 4 and MongoDB.',
    link: 'https://www.udemy.com/course/the-complete-web-development-bootcamp/',
    github: 'https://github.com/tonidalmases/keeper',
  },
  {
    name: 'The Complete Angular Course: Beginner to Advanced',
    date: '2020',
    time: '30 hours',
    platform: 'Udemy',
    description: 'Build real client apps with Angular, write clean and maintainable code and apply best practices when building Angular apps.',
    link: 'https://www.udemy.com/course/the-complete-angular-master-class/',
    github: 'https://github.com/tonidalmases/e-shop',
  },
  {
    name: 'Hands on With Docker & Docker Compose From a Docker Captain',
    date: '2020',
    time: '5 hours',
    platform: 'Udemy',
    description: 'Build, run and push your own custom Docker images and manage real world web applications with Docker',
    link: 'https://www.udemy.com/course/hands-on-with-docker-and-docker-compose/',
  },
  {
    name: 'Analyzing Data with Python',
    date: '2018',
    time: '15 hours',
    platform: 'edX',
    description: 'Learn how to analyze data in Python using multi-dimensional arrays in NumPy, manipulate DataFrames in Pandas, use SciPy library of mathematical routines, and perform machine learning using Scikit-learn.',
    link: 'https://www.edx.org/course/analyzing-data-with-python',
  },
  {
    name: 'Bitcoin and Cryptocurrency Technologies',
    date: '2018',
    time: '50 hours',
    platform: 'Coursera',
    description: 'Learn the technological side of the cryptocurrencies, and specially the Bitcoin.',
    link: 'https://www.coursera.org/learn/cryptocurrency',
  },
  {
    name: 'Machine Learning',
    date: '2017',
    time: '50 hours',
    platform: 'Coursera',
    description: 'Broad introduction to machine learning, data mining, and statistical pattern recognition.',
    link: 'https://www.coursera.org/learn/machine-learning',
  },
];
